<h3> Przekształcenia kontekstowe </h3>

Przkeształcenia kontekstowe uwzględniają sąsiedztwo piksela. Oznacza to że wyjściowa wartość piksela żależy również od jego sąsiedztwa. Odbywa się to za pomocą "maski", która przykrywa dany fragment obrazy dokonując jakiejś operacji.

In [5]:
#Importy
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
from collections import OrderedDict

In [6]:
#Kod biblioteki
def wczytaj_obraz(sciezka):
    return Image.open(sciezka)

def obraz_do_macierz(obraz):
    return np.array(obraz)

def macierz_do_obraz(macierz):
    return Image.fromarray(macierz.astype(np.uint8))

def rozbij_na_kanaly(obraz):
    macierz = obraz_do_macierz(obraz)
    k1 = macierz[:,:,0]
    k2 = macierz[:,:,1]
    k3 = macierz[:,:,2]
    return k1, k2, k3

def zloz(kanal1,kanal2,kanal3):
    macierz = np.stack((kanal1, kanal2, kanal3),axis=2)
    return macierz_do_obraz(macierz)

def obrot(obraz):
    macierz = obraz_do_macierz(obraz)
    obrocona = np.rot90(macierz)
    return macierz_do_obraz(obrocona)

def odbicie(obraz):
    macierz = obraz_do_macierz(obraz)
    obrocona = np.fliplr(macierz)
    return macierz_do_obraz(obrocona)

def zlicz(macierz):
    zliczenie = OrderedDict()
    for wiersz in macierz.tolist():
        for wartosc in wiersz:
            if wartosc in zliczenie.keys():
                zliczenie[wartosc] += 1
            else:
                zliczenie[wartosc] = 1
    return zliczenie

def histogram(obraz):
    k1, k2, k3 = rozbij_na_kanaly(obraz)
    histR = zlicz(k1)
    histG = zlicz(k2)
    histB = zlicz(k3)
    plt.figure(figsize=(15,15))
    plt.subplot(4,1,1)
    plt.bar(histR.keys(), histR.values(), color = 'red', alpha = .8, width = 1)
    
    plt.subplot(4,1,2)
    plt.bar(histG.keys(), histG.values(), color = 'green', alpha = .8, width = 1)
    
    plt.subplot(4,1,3)
    plt.bar(histB.keys(), histB.values(), color = 'blue', alpha = .8, width = 1)

    plt.subplot(4,1,4)
    plt.bar(histR.keys(), histR.values(), color = 'red', alpha = .8, width = 1)
    plt.bar(histG.keys(), histG.values(), color = 'green', alpha = .8, width = 1)
    plt.bar(histB.keys(), histB.values(), color = 'blue', alpha = .8, width = 1)

def negacja(obraz):
    macierz = obraz_do_macierz(obraz)
    macierz = 255 - macierz
    nowy_obraz = macierz_do_obraz(macierz)
    return nowy_obraz

def jasnosc(obraz, wartosc):
    macierz = obraz_do_macierz(obraz)
    LUT = np.arange(256)
    LUT += wartosc
    LUT = np.clip(LUT,0,255)
    for kanal in range(macierz.shape[2]):
        for x in range(macierz.shape[0]):
            for y in range(macierz.shape[1]):
                nowa_wartosc =  LUT[macierz[x,y,kanal]]
                if nowa_wartosc > 255:
                    nowa_wartosc = 255
                elif nowa_wartosc < 0:
                    nowa_wartosc = 0
                macierz[x,y,kanal] = nowa_wartosc
    nowy_obraz = macierz_do_obraz(macierz)
    return nowy_obraz

def kontrast(obraz, prog):
    macierz = obraz_do_macierz(obraz)
    LUT = np.arange(256)
    LUT = ((LUT - prog)*255)/(255-(2*prog))
    LUT = np.clip(LUT,0,255)
    for kanal in range(macierz.shape[2]):
        for x in range(macierz.shape[0]):
            for y in range(macierz.shape[1]):
                nowa_wartosc = LUT[macierz[x,y,kanal]]
                macierz[x,y,kanal] = nowa_wartosc
    nowy_obraz = macierz_do_obraz(macierz)
    return nowy_obraz

<h4> Filtry liniowe </h4>
    
Są to tak zwane operacje konwolucji, czyli przeplatania dwóch macierzy. Obraz przemnażany jest przez maskę w celu uzyskania żądanego efektu. Wyróżniamy dwa rozdaje filtrów:

    Dolnoprzepustowe
    
    Górnoprzepustowe

In [ ]:
def filtr_dolno(obraz,maska):

                
    return nowy_obraz


filtr_dolno(wczytaj_obraz("Lena.png"),np.ones((3,3)))

In [12]:
def filtr_gorno(obraz,maska):
    macierz = obraz_do_macierz(obraz)
    kopia = macierz.copy()
    offset = maska.shape[0]//2
    for kanal in range(macierz.shape[2]):
        for x in range(offset,macierz.shape[0]+offset):
            for y in range(offset,macierz.shape[1]+offset):
                fragment = macierz[x-offset:x+offset+1,y-offset:y+offset+1,kanal]
                fragment = fragment*maska
                print(maska)
                nowa_wartosc = abs(fragment.sum())
                kopia[x,y,kanal] = nowa_wartosc
    nowy_obraz = macierz_do_obraz(macierz)
    return nowy_obraz

filtr_gorno(wczytaj_obraz("Lena.png"),np.array([[0,0,0],[-1,0,0],[0,1,0]]))

[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[[ 0  0  0]
 [-1  0  0]
 [ 0  1  0]]
[

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 